"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 14:36:51.490233
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('subsidiary_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('event_id', name=op.f('uq_audit_log_event_id')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_log_hash'))
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_mine_id'), 'audit_log', ['mine_id'], unique=False)
    op.create_index(op.f('ix_audit_log_subsidiary_id'), 'audit_log', ['subsidiary_id'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('ml_models',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_samples', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_models'))
    )
    op.create_index(op.f('ix_ml_models_name'), 'ml_models', ['name'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_outbox_events_event_id'))
    )
    op.create_index('ix_outbox_unpublished', 'outbox_events', ['id'], unique=False, postgresql_where='published_at IS NULL')
    op.create_table('processed_events',
    sa.Column('consumer', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('consumer', 'event_id', name=op.f('pk_processed_events'))
    )
    op.create_table('regulations',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('act', sa.String(length=200), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.Enum('safety', 'environment', 'production', 'labour', name='ck_regulations_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('authority', sa.String(length=120), nullable=True),
    sa.Column('is_embedded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulations'))
    )
    op.create_index(op.f('ix_regulations_category'), 'regulations', ['category'], unique=False)
    op.create_index(op.f('ix_regulations_code'), 'regulations', ['code'], unique=True)
    op.create_table('risk_scores',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores'))
    )
    op.create_index('ix_risk_entity_time', 'risk_scores', ['entity_type', 'entity_id', 'computed_at'], unique=False)
    op.create_table('subsidiaries',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('headquarters', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subsidiaries'))
    )
    op.create_index(op.f('ix_subsidiaries_code'), 'subsidiaries', ['code'], unique=True)
    op.create_table('contractors',
    sa.Column('subsidiary_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration_no', sa.String(length=64), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=1024), nullable=True),
    sa.Column('contact_phone', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending_verification', 'active', 'suspended', 'blacklisted', name='ck_contractors_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.id'], name=op.f('fk_contractors_subsidiary_id_subsidiaries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractors')),
    sa.UniqueConstraint('gstin', name=op.f('uq_contractors_gstin')),
    sa.UniqueConstraint('registration_no', name=op.f('uq_contractors_registration_no'))
    )
    op.create_index(op.f('ix_contractors_name'), 'contractors', ['name'], unique=False)
    op.create_index(op.f('ix_contractors_status'), 'contractors', ['status'], unique=False)
    op.create_index(op.f('ix_contractors_subsidiary_id'), 'contractors', ['subsidiary_id'], unique=False)
    op.create_table('mines',
    sa.Column('subsidiary_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mine_type', sa.Enum('opencast', 'underground', 'mixed', name='ck_mines_mine_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('boundary_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capacity_mtpa', sa.Float(), nullable=True),
    sa.Column('workforce', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.id'], name=op.f('fk_mines_subsidiary_id_subsidiaries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mines'))
    )
    op.create_index(op.f('ix_mines_code'), 'mines', ['code'], unique=True)
    op.create_index(op.f('ix_mines_name'), 'mines', ['name'], unique=False)
    op.create_index(op.f('ix_mines_subsidiary_id'), 'mines', ['subsidiary_id'], unique=False)
    op.create_table('contracts',
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('work_order_no', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('value_inr', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('workforce_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'terminated', name='ck_contracts_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_contracts_contractor_id_contractors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_contracts_mine_id_mines'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts')),
    sa.UniqueConstraint('work_order_no', name=op.f('uq_contracts_work_order_no'))
    )
    op.create_index(op.f('ix_contracts_contractor_id'), 'contracts', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contracts_mine_id'), 'contracts', ['mine_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=512), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'corporate', 'mine_official', 'regulator', 'contractor', name='ck_users_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'disabled', name='ck_users_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('subsidiary_id', sa.UUID(), nullable=True),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_request_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_users_contractor_id_contractors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_users_mine_id_mines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.id'], name=op.f('fk_users_subsidiary_id_subsidiaries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('sso_subject', name='uq_users_sso_subject')
    )
    op.create_index(op.f('ix_users_contractor_id'), 'users', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mine_id'), 'users', ['mine_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_subsidiary_id'), 'users', ['subsidiary_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('anomalies',
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('recurring_violation', 'operational', 'attendance_drop', 'geofence', name='ck_anomalies_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='ck_anomalies_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_anomalies_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_anomalies_mine_id_mines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomalies'))
    )
    op.create_index(op.f('ix_anomalies_kind'), 'anomalies', ['kind'], unique=False)
    op.create_index(op.f('ix_anomalies_mine_id'), 'anomalies', ['mine_id'], unique=False)
    op.create_index('ix_anomaly_fingerprint_status', 'anomalies', ['fingerprint', 'status'], unique=False)
    op.create_table('attendance_records',
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('worker_name', sa.String(length=200), nullable=False),
    sa.Column('worker_id_no', sa.String(length=512), nullable=True),
    sa.Column('shift', sa.Enum('A', 'B', 'C', 'general', name='ck_attendance_records_shift', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_verified', sa.Boolean(), nullable=False),
    sa.Column('client_event_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_attendance_records_contractor_id_contractors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_attendance_records_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_attendance_records_recorded_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('client_event_id', name=op.f('uq_attendance_records_client_event_id'))
    )
    op.create_index('ix_attendance_mine_time', 'attendance_records', ['mine_id', 'check_in_at'], unique=False)
    op.create_index(op.f('ix_attendance_records_contractor_id'), 'attendance_records', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_mine_id'), 'attendance_records', ['mine_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('subsidiary_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.Enum('statutory_return', 'inspection_report', 'permit', 'license', 'circular', 'regulation', 'evidence', 'other', name='ck_documents_doc_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('ocr_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='ck_documents_ocr_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedded_chunks', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_documents_mine_id_mines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.id'], name=op.f('fk_documents_subsidiary_id_subsidiaries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_mine_id'), 'documents', ['mine_id'], unique=False)
    op.create_index(op.f('ix_documents_ocr_status'), 'documents', ['ocr_status'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_documents_subsidiary_id'), 'documents', ['subsidiary_id'], unique=False)
    op.create_table('inspections',
    sa.Column('number', sa.BigInteger(), sa.Identity(always=False, start=1001), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=False),
    sa.Column('inspection_type', sa.Enum('routine', 'safety', 'environmental', 'compliance_audit', 'statutory', 'reinspection', name='ck_inspections_inspection_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_accuracy_m', sa.Float(), nullable=True),
    sa.Column('distance_from_mine_km', sa.Float(), nullable=True),
    sa.Column('geo_verified', sa.Boolean(), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'processing', 'reviewed', name='ck_inspections_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('outcome', sa.Enum('compliant', 'minor_issues', 'non_compliant', 'pending', name='ck_inspections_outcome', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('client_event_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], name=op.f('fk_inspections_inspector_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_inspections_mine_id_mines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections')),
    sa.UniqueConstraint('client_event_id', name=op.f('uq_inspections_client_event_id')),
    sa.UniqueConstraint('number', name=op.f('uq_inspections_number'))
    )
    op.create_index(op.f('ix_inspections_inspected_at'), 'inspections', ['inspected_at'], unique=False)
    op.create_index(op.f('ix_inspections_inspector_id'), 'inspections', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_inspections_mine_id'), 'inspections', ['mine_id'], unique=False)
    op.create_index('ix_inspections_mine_time', 'inspections', ['mine_id', 'inspected_at'], unique=False)
    op.create_index(op.f('ix_inspections_outcome'), 'inspections', ['outcome'], unique=False)
    op.create_table('media_files',
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_media_files_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_media_files_storage_key'))
    )
    op.create_index('ix_media_entity', 'media_files', ['entity_type', 'entity_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='ck_notifications_severity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('source_event_id', sa.String(length=64), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('scope', sa.Enum('mine', 'subsidiary', 'national', name='ck_reports_scope', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='ck_reports_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('pdf_key', sa.String(length=512), nullable=True),
    sa.Column('xlsx_key', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled', sa.Boolean(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_reports_requested_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_scope_id'), 'reports', ['scope_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('compliance_items',
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('safety', 'environment', 'production', 'labour', name='ck_compliance_items_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regulation_id', sa.UUID(), nullable=True),
    sa.Column('regulation_ref', sa.String(length=200), nullable=True),
    sa.Column('frequency', sa.Enum('one_time', 'monthly', 'quarterly', 'half_yearly', 'annual', name='ck_compliance_items_frequency', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('compliant', 'due', 'in_progress', 'overdue', 'violated', name='ck_compliance_items_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_completed_by', sa.UUID(), nullable=True),
    sa.Column('evidence_document_id', sa.UUID(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_compliance_items_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_compliance_items_evidence_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_completed_by'], ['users.id'], name=op.f('fk_compliance_items_last_completed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_compliance_items_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_compliance_items_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], name=op.f('fk_compliance_items_regulation_id_regulations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_items'))
    )
    op.create_index(op.f('ix_compliance_items_category'), 'compliance_items', ['category'], unique=False)
    op.create_index(op.f('ix_compliance_items_due_date'), 'compliance_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_compliance_items_mine_id'), 'compliance_items', ['mine_id'], unique=False)
    op.create_index('ix_compliance_items_mine_status_due', 'compliance_items', ['mine_id', 'status', 'due_date'], unique=False)
    op.create_index(op.f('ix_compliance_items_owner_id'), 'compliance_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_compliance_items_status'), 'compliance_items', ['status'], unique=False)
    op.create_table('violations',
    sa.Column('number', sa.BigInteger(), sa.Identity(always=False, start=1001), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=True),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('violation', 'safety_observation', 'incident', name='ck_violations_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('category', sa.Enum('safety', 'environment', 'production', 'labour', name='ck_violations_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='ck_violations_severity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('severity_confirmed', sa.Boolean(), nullable=False),
    sa.Column('ai_suggested_severity', sa.Enum('low', 'medium', 'high', 'critical', name='ck_violations_ai_suggested_severity', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('ai_source', sa.String(length=16), nullable=True),
    sa.Column('detected_by', sa.Enum('ai', 'human', name='ck_violations_detected_by', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'action_assigned', 'pending_verification', 'escalated', 'closed', name='ck_violations_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('regulation_ref', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_event_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_violations_confirmed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_violations_contractor_id_contractors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_violations_inspection_id_inspections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_violations_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_violations_reported_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_violations')),
    sa.UniqueConstraint('client_event_id', name=op.f('uq_violations_client_event_id')),
    sa.UniqueConstraint('number', name=op.f('uq_violations_number'))
    )
    op.create_index(op.f('ix_violations_category'), 'violations', ['category'], unique=False)
    op.create_index(op.f('ix_violations_contractor_id'), 'violations', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_violations_inspection_id'), 'violations', ['inspection_id'], unique=False)
    op.create_index('ix_violations_mine_category_time', 'violations', ['mine_id', 'category', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_violations_mine_id'), 'violations', ['mine_id'], unique=False)
    op.create_index('ix_violations_mine_status', 'violations', ['mine_id', 'status'], unique=False)
    op.create_index(op.f('ix_violations_occurred_at'), 'violations', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_violations_severity'), 'violations', ['severity'], unique=False)
    op.create_index(op.f('ix_violations_status'), 'violations', ['status'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('violation_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'submitted', 'verified', 'rejected', 'overdue', name='ck_corrective_actions_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('reinspection_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_corrective_actions_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_corrective_actions_assigned_to_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reinspection_id'], ['inspections.id'], name=op.f('fk_corrective_actions_reinspection_id_inspections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_corrective_actions_verified_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], name=op.f('fk_corrective_actions_violation_id_violations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrective_actions'))
    )
    op.create_index(op.f('ix_corrective_actions_assigned_to'), 'corrective_actions', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_corrective_actions_deadline'), 'corrective_actions', ['deadline'], unique=False)
    op.create_index(op.f('ix_corrective_actions_status'), 'corrective_actions', ['status'], unique=False)
    op.create_index(op.f('ix_corrective_actions_violation_id'), 'corrective_actions', ['violation_id'], unique=False)
    # ### end Alembic commands ###

    # Audit trail is write-once: any UPDATE/DELETE/TRUNCATE is rejected by the database itself,
    # independently of application permissions (tamper-evidence also comes from the hash chain).
    op.execute("""
        CREATE OR REPLACE FUNCTION cmg_audit_log_immutable() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only (% not permitted)', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_log_no_update_delete
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION cmg_audit_log_immutable();
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_log_no_truncate
        BEFORE TRUNCATE ON audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION cmg_audit_log_immutable();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_no_truncate ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_no_update_delete ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS cmg_audit_log_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corrective_actions_violation_id'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_status'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_deadline'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_assigned_to'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_violations_status'), table_name='violations')
    op.drop_index(op.f('ix_violations_severity'), table_name='violations')
    op.drop_index(op.f('ix_violations_occurred_at'), table_name='violations')
    op.drop_index('ix_violations_mine_status', table_name='violations')
    op.drop_index(op.f('ix_violations_mine_id'), table_name='violations')
    op.drop_index('ix_violations_mine_category_time', table_name='violations')
    op.drop_index(op.f('ix_violations_inspection_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_contractor_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_category'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_compliance_items_status'), table_name='compliance_items')
    op.drop_index(op.f('ix_compliance_items_owner_id'), table_name='compliance_items')
    op.drop_index('ix_compliance_items_mine_status_due', table_name='compliance_items')
    op.drop_index(op.f('ix_compliance_items_mine_id'), table_name='compliance_items')
    op.drop_index(op.f('ix_compliance_items_due_date'), table_name='compliance_items')
    op.drop_index(op.f('ix_compliance_items_category'), table_name='compliance_items')
    op.drop_table('compliance_items')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_reports_scope_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_media_entity', table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_inspections_outcome'), table_name='inspections')
    op.drop_index('ix_inspections_mine_time', table_name='inspections')
    op.drop_index(op.f('ix_inspections_mine_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspector_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspected_at'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_documents_subsidiary_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_ocr_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_mine_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_attendance_records_mine_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_contractor_id'), table_name='attendance_records')
    op.drop_index('ix_attendance_mine_time', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('ix_anomaly_fingerprint_status', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_mine_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_kind'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_subsidiary_id'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_mine_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_contractor_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_contracts_mine_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contractor_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_mines_subsidiary_id'), table_name='mines')
    op.drop_index(op.f('ix_mines_name'), table_name='mines')
    op.drop_index(op.f('ix_mines_code'), table_name='mines')
    op.drop_table('mines')
    op.drop_index(op.f('ix_contractors_subsidiary_id'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_status'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_name'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_subsidiaries_code'), table_name='subsidiaries')
    op.drop_table('subsidiaries')
    op.drop_index('ix_risk_entity_time', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_regulations_code'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_category'), table_name='regulations')
    op.drop_table('regulations')
    op.drop_table('processed_events')
    op.drop_index('ix_outbox_unpublished', table_name='outbox_events', postgresql_where='published_at IS NULL')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_ml_models_name'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_subsidiary_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_mine_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
