"""grievances production environment

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 14:05:45.870684
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grievances',
    sa.Column('number', sa.BigInteger(), sa.Identity(always=False, start=5001), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=True),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Enum('wages', 'safety', 'working_conditions', 'harassment', 'welfare', 'contractor_dispute', 'environment', 'other', name=op.f('ck_grievances_category'), native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name=op.f('ck_grievances_priority'), native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'assigned', 'in_progress', 'resolved', 'closed', 'rejected', name=op.f('ck_grievances_status'), native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('reopen_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_grievances_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_grievances_contractor_id_contractors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_grievances_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], name=op.f('fk_grievances_raised_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_grievances_resolved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grievances')),
    sa.UniqueConstraint('number', name=op.f('uq_grievances_number'))
    )
    op.create_index(op.f('ix_grievances_assigned_to'), 'grievances', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_grievances_category'), 'grievances', ['category'], unique=False)
    op.create_index(op.f('ix_grievances_contractor_id'), 'grievances', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_grievances_due_at'), 'grievances', ['due_at'], unique=False)
    op.create_index(op.f('ix_grievances_mine_id'), 'grievances', ['mine_id'], unique=False)
    op.create_index('ix_grievances_mine_status', 'grievances', ['mine_id', 'status'], unique=False)
    op.create_index(op.f('ix_grievances_priority'), 'grievances', ['priority'], unique=False)
    op.create_index(op.f('ix_grievances_raised_by'), 'grievances', ['raised_by'], unique=False)
    op.create_index(op.f('ix_grievances_status'), 'grievances', ['status'], unique=False)
    op.create_table('production_records',
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('target_t', sa.Float(), nullable=True),
    sa.Column('produced_t', sa.Float(), nullable=False),
    sa.Column('dispatched_t', sa.Float(), nullable=False),
    sa.Column('overburden_bcm', sa.Float(), nullable=True),
    sa.Column('closing_stock_t', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_production_records_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_production_records_recorded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_records')),
    sa.UniqueConstraint('mine_id', 'period', name='uq_production_mine_period')
    )
    op.create_index(op.f('ix_production_records_mine_id'), 'production_records', ['mine_id'], unique=False)
    op.create_index(op.f('ix_production_records_period'), 'production_records', ['period'], unique=False)
    op.create_table('environment_readings',
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('parameter', sa.Enum('pm10', 'pm2_5', 'so2', 'no2', 'noise_day', 'noise_night', 'water_ph', 'water_tss', 'water_oil_grease', 'water_cod', name=op.f('ck_environment_readings_parameter'), native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('limit_min', sa.Float(), nullable=True),
    sa.Column('limit_max', sa.Float(), nullable=True),
    sa.Column('exceeded', sa.Boolean(), nullable=False),
    sa.Column('station', sa.String(length=120), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('violation_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_environment_readings_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_environment_readings_recorded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], name=op.f('fk_environment_readings_violation_id_violations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environment_readings'))
    )
    op.create_index('ix_env_mine_param_time', 'environment_readings', ['mine_id', 'parameter', 'sampled_at'], unique=False)
    op.create_index(op.f('ix_environment_readings_exceeded'), 'environment_readings', ['exceeded'], unique=False)
    op.create_index(op.f('ix_environment_readings_mine_id'), 'environment_readings', ['mine_id'], unique=False)
    op.create_index(op.f('ix_environment_readings_parameter'), 'environment_readings', ['parameter'], unique=False)
    op.create_index(op.f('ix_environment_readings_sampled_at'), 'environment_readings', ['sampled_at'], unique=False)
    # ### end Alembic commands ###

    # Violations raised by automated limit checks carry detected_by = 'system'.
    op.drop_constraint(op.f('ck_violations_detected_by'), 'violations', type_='check')
    op.create_check_constraint(op.f('ck_violations_detected_by'), 'violations', "detected_by IN ('ai', 'human', 'system')")


def downgrade() -> None:
    op.execute("UPDATE violations SET detected_by = 'human' WHERE detected_by = 'system'")
    op.drop_constraint(op.f('ck_violations_detected_by'), 'violations', type_='check')
    op.create_check_constraint(op.f('ck_violations_detected_by'), 'violations', "detected_by IN ('ai', 'human')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_environment_readings_sampled_at'), table_name='environment_readings')
    op.drop_index(op.f('ix_environment_readings_parameter'), table_name='environment_readings')
    op.drop_index(op.f('ix_environment_readings_mine_id'), table_name='environment_readings')
    op.drop_index(op.f('ix_environment_readings_exceeded'), table_name='environment_readings')
    op.drop_index('ix_env_mine_param_time', table_name='environment_readings')
    op.drop_table('environment_readings')
    op.drop_index(op.f('ix_production_records_period'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_mine_id'), table_name='production_records')
    op.drop_table('production_records')
    op.drop_index(op.f('ix_grievances_status'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_raised_by'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_priority'), table_name='grievances')
    op.drop_index('ix_grievances_mine_status', table_name='grievances')
    op.drop_index(op.f('ix_grievances_mine_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_due_at'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_contractor_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_category'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_assigned_to'), table_name='grievances')
    op.drop_table('grievances')
    # ### end Alembic commands ###
